CREATE TABLE market_event_templates (
    template_id VARCHAR(96) PRIMARY KEY,
    rarity VARCHAR(16) NOT NULL,
    scope VARCHAR(16) NOT NULL,
    automatic_weight INTEGER NOT NULL,
    automatic_enabled BOOLEAN NOT NULL,
    blocking_allowed BOOLEAN NOT NULL,
    min_duration_seconds BIGINT NOT NULL,
    max_duration_seconds BIGINT NOT NULL,
    min_effect_basis_points INTEGER NOT NULL,
    max_effect_basis_points INTEGER NOT NULL,
    effect_direction VARCHAR(16) NOT NULL,
    cooldown_seconds BIGINT NOT NULL,
    player_facing_name VARCHAR(255) NOT NULL,
    player_facing_description VARCHAR(2048) NOT NULL,
    broad_scope_hint VARCHAR(255) NOT NULL,
    eligible_target_metadata VARCHAR(4096) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE market_event_instances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id VARCHAR(96) NOT NULL,
    source VARCHAR(16) NOT NULL,
    rarity VARCHAR(16) NOT NULL,
    scope VARCHAR(16) NOT NULL,
    selected_category_id VARCHAR(64) NULL,
    selected_item_ids VARCHAR(4096) NULL,
    effect_basis_points INTEGER NOT NULL,
    effect_version INTEGER NOT NULL DEFAULT 1,
    blocking BOOLEAN NOT NULL DEFAULT FALSE,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(16) NOT NULL,
    end_reason VARCHAR(16) NULL,
    active_slot VARCHAR(64) NULL,
    actor VARCHAR(128) NULL,
    audit_metadata VARCHAR(4096) NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT fk_market_event_instances_template
        FOREIGN KEY (template_id) REFERENCES market_event_templates (template_id),
    CONSTRAINT chk_market_event_instances_target
        CHECK (
            (scope = 'CATEGORY' AND selected_category_id IS NOT NULL)
            OR (scope IN ('ITEM', 'ITEM_SET') AND selected_item_ids IS NOT NULL)
            OR (scope = 'MARKET_WIDE')
        ),
    CONSTRAINT chk_market_event_instances_time
        CHECK (ends_at > started_at)
);

CREATE UNIQUE INDEX uq_market_event_instances_active_slot
    ON market_event_instances (active_slot);

CREATE INDEX idx_market_event_instances_status_time
    ON market_event_instances (status, started_at, ends_at);

CREATE INDEX idx_market_event_instances_template
    ON market_event_instances (template_id);
