package io.github.HenriqueMichelini.craftalism.api.service;

import java.util.List;
import org.springframework.stereotype.Component;

@Component
public class DefaultMarketCatalog {

    private static final List<MarketSeedItem> ITEMS = List.of(
        new MarketSeedItemBuilder()
            .itemId("wheat")
            .categoryId("farming")
            .categoryDisplayName("Farming")
            .displayName("Wheat")
            .iconKey("WHEAT")
            .variationPercent("2.3")
            .baseUnitPrice(50000L)
            .minUnitPrice(25000L)
            .maxUnitPrice(150000L)
            .segmentSize(50L)
            .priceSensitivity("0.0800")
            .baseRegenQuantity(1L)
            .regenIntervalSeconds(60L)
            .build(),
        new MarketSeedItemBuilder()
            .itemId("carrot")
            .categoryId("farming")
            .categoryDisplayName("Farming")
            .displayName("Carrot")
            .iconKey("CARROT")
            .variationPercent("-1.4")
            .baseUnitPrice(10000L)
            .minUnitPrice(5000L)
            .maxUnitPrice(30000L)
            .segmentSize(50L)
            .priceSensitivity("0.0800")
            .baseRegenQuantity(1L)
            .regenIntervalSeconds(60L)
            .build(),
        new MarketSeedItemBuilder()
            .itemId("potato")
            .categoryId("farming")
            .categoryDisplayName("Farming")
            .displayName("Potato")
            .iconKey("POTATO")
            .variationPercent("0.8")
            .baseUnitPrice(12000L)
            .minUnitPrice(6000L)
            .maxUnitPrice(36000L)
            .segmentSize(50L)
            .priceSensitivity("0.0800")
            .baseRegenQuantity(1L)
            .regenIntervalSeconds(60L)
            .build(),
        new MarketSeedItemBuilder()
            .itemId("sugar_cane")
            .categoryId("farming")
            .categoryDisplayName("Farming")
            .displayName("Sugar Cane")
            .iconKey("SUGAR_CANE")
            .variationPercent("1.7")
            .baseUnitPrice(18000L)
            .minUnitPrice(9000L)
            .maxUnitPrice(54000L)
            .segmentSize(50L)
            .priceSensitivity("0.0800")
            .baseRegenQuantity(1L)
            .regenIntervalSeconds(60L)
            .build(),
        new MarketSeedItemBuilder()
            .itemId("oak_log")
            .categoryId("forestry")
            .categoryDisplayName("Forestry")
            .displayName("Oak Log")
            .iconKey("OAK_LOG")
            .variationPercent("-0.2")
            .baseUnitPrice(25000L)
            .minUnitPrice(12500L)
            .maxUnitPrice(75000L)
            .segmentSize(50L)
            .priceSensitivity("0.0800")
            .baseRegenQuantity(1L)
            .regenIntervalSeconds(60L)
            .build(),
        new MarketSeedItemBuilder()
            .itemId("spruce_log")
            .categoryId("forestry")
            .categoryDisplayName("Forestry")
            .displayName("Spruce Log")
            .iconKey("SPRUCE_LOG")
            .variationPercent("0.4")
            .baseUnitPrice(28000L)
            .minUnitPrice(14000L)
            .maxUnitPrice(84000L)
            .segmentSize(50L)
            .priceSensitivity("0.0800")
            .baseRegenQuantity(1L)
            .regenIntervalSeconds(60L)
            .build(),
        new MarketSeedItemBuilder()
            .itemId("cobblestone")
            .categoryId("mining")
            .categoryDisplayName("Mining")
            .displayName("Cobblestone")
            .iconKey("COBBLESTONE")
            .variationPercent("-0.8")
            .baseUnitPrice(4000L)
            .minUnitPrice(2000L)
            .maxUnitPrice(12000L)
            .segmentSize(50L)
            .priceSensitivity("0.0800")
            .baseRegenQuantity(1L)
            .regenIntervalSeconds(60L)
            .build(),
        new MarketSeedItemBuilder()
            .itemId("coal")
            .categoryId("mining")
            .categoryDisplayName("Mining")
            .displayName("Coal")
            .iconKey("COAL")
            .variationPercent("0.9")
            .baseUnitPrice(35000L)
            .minUnitPrice(17500L)
            .maxUnitPrice(105000L)
            .segmentSize(50L)
            .priceSensitivity("0.0800")
            .baseRegenQuantity(1L)
            .regenIntervalSeconds(60L)
            .build(),
        new MarketSeedItemBuilder()
            .itemId("iron_ingot")
            .categoryId("mining")
            .categoryDisplayName("Mining")
            .displayName("Iron Ingot")
            .iconKey("IRON_INGOT")
            .variationPercent("1.1")
            .baseUnitPrice(140000L)
            .minUnitPrice(70000L)
            .maxUnitPrice(420000L)
            .segmentSize(50L)
            .priceSensitivity("0.0800")
            .baseRegenQuantity(1L)
            .regenIntervalSeconds(60L)
            .build(),
        new MarketSeedItemBuilder()
            .itemId("gold_ingot")
            .categoryId("mining")
            .categoryDisplayName("Mining")
            .displayName("Gold Ingot")
            .iconKey("GOLD_INGOT")
            .variationPercent("2.8")
            .baseUnitPrice(220000L)
            .minUnitPrice(110000L)
            .maxUnitPrice(660000L)
            .segmentSize(50L)
            .priceSensitivity("0.0800")
            .baseRegenQuantity(1L)
            .regenIntervalSeconds(60L)
            .build(),
        new MarketSeedItemBuilder()
            .itemId("diamond")
            .categoryId("mining")
            .categoryDisplayName("Mining")
            .displayName("Diamond")
            .iconKey("DIAMOND")
            .variationPercent("4.5")
            .baseUnitPrice(900000L)
            .minUnitPrice(450000L)
            .maxUnitPrice(2700000L)
            .segmentSize(50L)
            .priceSensitivity("0.0800")
            .baseRegenQuantity(1L)
            .regenIntervalSeconds(60L)
            .build()
    );

    public List<MarketSeedItem> items() {
        return ITEMS;
    }
}
